// Code generated by "stringer -type Severity -output severity_string.go -trimprefix Severity -linecomment"; DO NOT EDIT.

package notifier

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[severityUnknown-0]
	_ = x[SeverityInfo-1]
	_ = x[SeverityWarning-2]
	_ = x[SeverityCritical-3]
	_ = x[severitySentinel-4]
}

const _Severity_name = "severityUnknownINFOWARNINGCRITICALseveritySentinel"

var _Severity_index = [...]uint8{0, 15, 19, 26, 34, 50}

func (i Severity) String() string {
	if i < 0 || i >= Severity(len(_Severity_index)-1) {
		return "Severity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Severity_name[_Severity_index[i]:_Severity_index[i+1]]
}
